#!/bin/bash

arduino-cli compile --fqbn TinyCircuits:samd:tinyscreen .
echo "[make] dont forget to turn the fucking circuit off dummy"
arduino-cli upload -p /dev/ttyACM? --fqbn TinyCircuits:samd:tinyscreen .
arduino-cli monitor -p /dev/ttyACM? -c 9600
