#!/bin/bash
# Set variables
FQBN="TinyCircuits:samd:tinyscreen"
PORT="/dev/ttyACM?"   # adjust if needed
BUILD_DIR="build"

# Compile
arduino-cli compile --clean --fqbn $FQBN --build-path $BUILD_DIR src/
echo "[making] dont forget to unplug it"

# Upload
arduino-cli upload -p $PORT --fqbn $FQBN --input-dir $BUILD_DIR

# Monitor
arduino-cli monitor -p $PORT -c 9600

